# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReanalysisVisualization
                                 A QGIS plugin
 This plugin is for downloading and visualisation 
archived hydrometeorological data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-21
        copyright            : (C) 2020 by Frolov Mikhail
        email                : mishanya666666@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ReanalysisVisualization class from file ReanalysisVisualization.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .reanalysis_visualization import ReanalysisVisualization
    return ReanalysisVisualization(iface)
